name: Deploy to lip-stable

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to lip-stable branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: lip-stable       # Target branch
          folder: dist             # Build output folder
          clean: true              # Optional: remove existing files in target branch
